[package]
name = "archiver-rs"
version = "0.5.1"
authors = ["Chino Chang <chino@joymoe.com>"]
edition = "2018"
description = "A library for easy interaction with multiple archive formats"
documentation = "https://docs.rs/archiver-rs"
homepage = "https://github.com/JoyMoe/archiver-rs"
keywords = ["bzip2", "gzip", "tar", "xz", "zip"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/JoyMoe/archiver-rs"

[dependencies]
thiserror = "1.0"

bzip2 = { version = "0.4", optional = true }
flate2 = { version = "1.0", optional = true }
tar = { version = "0.4", optional = true }
xz2 = { version = "0.1", optional = true }

[dependencies.zip]
version = "0.5"
default-features = false
features = ["deflate", "time"]
optional = true

[features]
default = ["all"]
all = ["bzip", "gzip", "tar", "xz", "zip"]
bzip = ["bzip2", "zip/bzip2"]
gzip = ["flate2"]
xz = ["xz2"]
zip-all = ["zip", "zip/bzip2"]
